
services:
  minio:
    image: minio/minio:latest
    container_name: minio_hardware
    ports:
      - "9000:9000"  
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: minioadmin  
      MINIO_ROOT_PASSWORD: minioadmin  
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
